# Port de l?API Gateway
server.port=8080

# Nom du service
spring.application.name=API-GATEWAY

# Activer la découverte des services avec Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Adresse du serveur Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
